### ISSUE TITLE
Add to Terraform Registry

### ISSUE THREAD

**Issue by smazurov** [streamnative/terraform-provider-pulsar#18]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great if we could install this provider from Terraform Provider registry.

### References

https://github.com/hashicorp/terraform/tree/guide-v0.13-beta/provider-sources

**Comment by jiazhai** [comment]
Thanks @smazurov  for rise up this issue.

**Comment by sijie** [comment]
@smazurov Are you interested in driving the effort of adding it to the terraform registry?

**Comment by smazurov** [comment]
since this is under streamnative, probably not, if its under apache, then more likely. It shouldn't be too much work to get it initially submitted, and they have github actions to push new releases.

**Comment by smazurov** [comment]
Until this is resolved, it was blocking us, so we published a 1.0.0 to [quantummetric/pulsar](https://registry.terraform.io/providers/quantummetric/pulsar/latest)

**Comment by ielkhalloufi** [comment]
Is there any movement? I was surprised that I could not find anything in the terraform registry.

**Comment by nodece** [comment]
@ielkhalloufi Currently we don't add this to terraform registry,  #39 blocks our progress, we need to upgrade the SDK to v2 to support the latest terraform.

**Comment by jaak-pruulmann-sympower** [comment]
For the lack of the better place (and to signify the need to get an official provider..)..

It looks like the admin API has changed in 2.10 which makes it impossible to create non-partitioned topics with the existing provider from @smazurov . (Create fails, because the provider sends an integer as the request body while the server expects a map there now). 

Stepan, can you perhaps rebuild and upload a new one (with updated client that is compatible with 2.10?). We could choose the relevant version of the provider to match our broker version..

**Comment by nodece** [comment]
@jaak-pruulmann-sympower Thanks for your report! I submitted https://github.com/streamnative/terraform-provider-pulsar/pull/52 to fix this.

**Comment by maxsxu** [comment]
We've published `streamnative/pulsar:v0.1.0` to https://registry.terraform.io/providers/streamnative/pulsar/0.1.0
